#!/bin/sh -e
# converts html to markdown
# uses an available program to fetch URL and tidy to normalize it first

REQUIRED=tidy

THIS=${0##*/}

# Portable which(1).
pathfind () {
    ifs_save="$IFS"
    IFS=:
    for _p in $PATH; do
        if [ -x "$_p/$*" ] && [ -f "$_p/$*" ]; then
            IFS="$OLDIFS"
            return 0
        fi
    done
    IFS="$ifs_save"
    return 1
}

_iconv () {
    if [ -z "$ICONV_AVAIL" ] || pathfind iconv; then
	ICONV_AVAIL=yes
    fi

    if [ -z "$1" ]; then
	set --
    fi

    if [ "$ICONV_AVAIL" = "yes" ]; then
	iconv "$@"
    else
	cat "$1"
    fi
}

safein () {
    _iconv "$1" -t utf-8
}

safeout () {
    if [ -z "$1" ]; then
	_iconv -f utf-8
	return
    fi

    if [ -z "$2" ]; then
	src=${TMPDIR-/tmp}/${THIS}.$$
	dest="$1"
	trap "status=$?; rm -rf $src; exit $status" EXIT INT TERM
	_iconv -f utf-8 >$src
    else
	src="$1"
	dest="$2"
    fi

    is_target_exists=
    if [ -f "$dest" ]; then
	is_target_exists=1
	mv -f "$dest" "$dest~"
    fi

    mv -f "$src" "$dest"

    printf "Created $dest" >&2
    [ -z "$is_target_exists" ] || {
	printf " (previous file has been backed up as '$dest~')" >&2
    }
    echo >&2 .
}

for p in pandoc $REQUIRED; do
    pathfind $p || {
        echo >&2 "You need '$p' to use this program!"
        exit 1
    }
done

outfile=
while getopts o:h opt; do
    case $opt in
    o) outfile="$OPTARG" ;;
    h) echo >&2 "Usage: $THIS [-o output_file] [-h] [input_file]"; exit 2 ;;
    esac
done

shift $(($OPTIND - 1))

infile=
ignored=
while [ -n "$1" ]; do
    case "$1" in
    --)
	shift
	PANDOC_OPTS="$@"
	break ;;
    *)
	if [ -z "$infile" ]; then
	    infile="$1"
	else
	    ignored="$ignored$1"
	fi ;;
    esac
    shift
done

if [ -n "$ignored" ]; then
    echo >&2 "Excessive arguments '$ignored' will be ignored!"
fi

PANDOC_OPTS=${PANDOC_OPTS:+$PANDOC_OPTS}

if [ -n "$infile" ] && ! [ -f "$infile" ]; then
    echo >&2 "'$infile' not found"
    exit 1
fi

if [ -z "$infile" ] || [ -f "$infile" ]; then
    tidy -utf8 "$infile" 2>/dev/null | \
    pandoc $PANDOC_OPTS -r html -w markdown -s | safeout "$outfile"
else
    # Treat given argument as an URL.  Locate a
    # sensible text based browser (note the order).
    for p in wget lynx w3m curl links w3c; do
        if pathfind $p; then
            DUMPER=$p
            break
        fi
    done
    # Setup proper options.
    case "$DUMPER" in
        wget)  OPT="-O-" ;;
        lynx)  OPT="-source" ;;
        w3m)   OPT="-dump_source" ;;
        curl)  OPT="" ;;
        links) OPT="-source" ;;
        w3c)   OPT="-n -get" ;;
        "")    printf "Needs a program to fetch the URL " >&2
               printf "(e.g. wget, w3m, lynx, w3c, or curl)." >&2
               exit 1 ;;
    esac
    # Fetch and feed to pandoc.
    $DUMPER $OPT "$infile" 2>/dev/null | \
    tidy -utf8 "$infile" 2>/dev/null | \
    pandoc $PANDOC_OPTS -r html -w markdown -s | safeout "$outfile"
fi
